# Lecture 2.1: Pandas and structured datasets

In [1]:
import pandas as pd

**Pay attention!**
<br>Pandas is no longer updated on python 2.7 since January 2019 (instead it is so on python 3)

## Pandas dataframe, your new best friend

In general, you could say that the Pandas DataFrame consists of three main components: the data, the index, and the columns.

Firstly, the DataFrame can contain data that is:
- a Pandas DataFrame
- a Pandas Series: a one-dimensional labeled array capable of holding any data type with axis labels or index. An example of a Series object is one column from a DataFrame.
- a NumPy ndarray, which can be a record or structured

Structured arrays allow users to manipulate the data by named fields.

Record arrays, on the other hand, expand the properties of structured arrays. They allow users to access fields of structured arrays by attribute rather than by index.

### Your first dataframe

In [49]:
data = np.array([['','Col0','Col1'],
                ['Row0',0,1],
                ['Row1',2,3]])

In [50]:
cacca=pd.DataFrame(data=data[1:,1:],
                  index=data[1:,0],
                  columns=data[0,1:])

In [51]:
cacca

     Col0 Col1
Row0    0    1
Row1    2    3

**Indeces**

In [52]:
cacca.index

Index([u'Row0', u'Row1'], dtype='object')

**Columns**

In [53]:
cacca.columns

Index([u'Col0', u'Col1'], dtype='object')

Navigate in the DataFrame by **rows**: ***loc*** and ***iloc***.

In [54]:
cacca.loc['Row0']

Col0    0
Col1    1
Name: Row0, dtype: object

***loc*** works on the index name

In [55]:
cacca.iloc[0]

Col0    0
Col1    1
Name: Row0, dtype: object

***iloc*** works on the position

Navigate in the DataFrame by **columns** is much easier

In [56]:
cacca['Col0']

Row0    0
Row1    2
Name: Col0, dtype: object

In [57]:
cacca.Col0

Row0    0
Row1    2
Name: Col0, dtype: object

#### Modify the DataFrame

Add a **column**

In [24]:
cacca['Col2']=[2, 4]

In [25]:
cacca

     Col0 Col1  Col2
Row0    0    1     2
Row1    2    3     4

Add a **row**

In [26]:
cacca_2=pd.DataFrame(data=[[4,5,6]],
                  index=['Row2'],
                  columns=['Col0','Col1','Col2'])

In [27]:
cacca.append(cacca_2)

     Col0 Col1  Col2
Row0    0    1     2
Row1    2    3     4
Row2    4    5     6

In [28]:
cacca

     Col0 Col1  Col2
Row0    0    1     2
Row1    2    3     4

It creates a copy

In [29]:
cacca=cacca.append(cacca_2)

In [30]:
cacca

     Col0 Col1  Col2
Row0    0    1     2
Row1    2    3     4
Row2    4    5     6

Delete a **column**

In [31]:
del cacca['Col2']

In [32]:
cacca

     Col0 Col1
Row0    0    1
Row1    2    3
Row2    4    5

Delete a **row**

In [33]:
cacca.drop(cacca.index[0])

     Col0 Col1
Row1    2    3
Row2    4    5

In [34]:
cacca

     Col0 Col1
Row0    0    1
Row1    2    3
Row2    4    5

D'oh! drop returns a copy! In order to modify the original DataFrame, activate the option 'inplace'

In [35]:
cacca.drop(cacca.index[0], inplace=True)

In [36]:
cacca

     Col0 Col1
Row1    2    3
Row2    4    5

### Reading a csv file

In [44]:
imdb_votes=pd.read_csv('./data/imdb_2018_films_urls.txt', sep='\t')

***sep*** is quite straightforward. There are other interesting options, as: 
- ***header*** is which is the column to be used as description of the  column. Since we have none, we set it to none; 
- ***names*** is the name of the columns.

Since someone already fixed the structure of the file, for the moment you do not have to bother about column names or the header.

In [45]:
imdb_votes

,title,url,rating,metascore,votes,runtime
0,Avengers: Infinity War,https://www.imdb.com//title/tt4154756/?ref_=ad...,8.5,68,556607,149
1,Black Panther,https://www.imdb.com//title/tt1825683/?ref_=ad...,7.4,88,435846,134
2,Deadpool 2,https://www.imdb.com//title/tt5463162/?ref_=ad...,7.8,66,327083,119
3,Ready Player One,https://www.imdb.com//title/tt1677720/?ref_=ad...,7.5,64,259630,140
4,A Quiet Place,https://www.imdb.com//title/tt6644200/?ref_=ad...,7.6,82,249406,90
5,Mission: Impossible - Fallout,https://www.imdb.com//title/tt4912910/?ref_=ad...,7.9,86,198276,147
6,Venom,https://www.imdb.com//title/tt1270797/?ref_=ad...,6.8,35,197816,112
7,Annihilation,https://www.imdb.com//title/tt2798920/?ref_=ad...,6.9,79,194795,115
8,Jurassic World: Fallen Kingdom,https://www.imdb.com//title/tt4881806/?ref_=ad...,6.2,51,187521,128
9,Solo: A Star Wars Story,https://www.imdb.com//title/tt3778644/?ref_=ad...,7.0,62,187191,135
10,Ant-Man and the Wasp,https://www.imdb.com//title/tt5095030/?ref_=ad...,7.2,70,175967,118
11,Bohemian Rhapsody,https://www.imdb.com//title/tt1727824/?ref_=ad...,8.3,49,169065,134
12,Incredibles 2,https://www.imdb.com//title/tt3606756/?ref_=ad...,7.8,80,159121,118
13,Tomb Raider,https://www.imdb.com//title/tt1365519/?ref_=ad...,6.3,48,147098,119
14,Game Night,https://www.imdb.com//title/tt2704998/?ref_=ad...,7.0,66,138645,100
15,A Star Is Born,https://www.imdb.com//title/tt1517451/?ref_=ad...,8.1,88,125848,136
16,Red Sparrow,https://www.imdb.com//title/tt2873282/?ref_=ad...,6.6,53,119504,140
17,Hereditary,https://www.imdb.com//title/tt7784604/?ref_=ad...,7.3,87,117376,127
18,Ocean's Eight,https://www.imdb.com//title/tt5164214/?ref_=ad...,6.2,61,115541,110
19,Fantastic Beasts: The Crimes of Grindelwald,https://www.imdb.com//title/tt4123430/?ref_=ad...,6.8,52,101976,134
20,Аквамен,https://www.imdb.com//title/tt1477834/?ref_=ad...,7.5,55,101289,143
21,Bird Box,https://www.imdb.com//title/tt2737304/?ref_=ad...,6.8,52,100102,124
22,Rampage,https://www.imdb.com//title/tt2231461/?ref_=ad...,6.1,45,99624,107
23,The Meg,https://www.imdb.com//title/tt4779682/?ref_=ad...,5.7,46,88725,113
24,Isle of Dogs,https://www.imdb.com//title/tt5104604/?ref_=ad...,7.9,82,87168,101
25,Maze Runner: The Death Cure,https://www.imdb.com//title/tt4500922/?ref_=ad...,6.3,51,81807,143
26,Pacific Rim: Uprising,https://www.imdb.com//title/tt2557478/?ref_=ad...,5.6,44,80292,111
27,Апгрейд,https://www.imdb.com//title/tt6499752/?ref_=ad...,7.6,67,77662,100
28,The Cloverfield Paradox,https://www.imdb.com//title/tt2548396/?ref_=ad...,5.6,37,76384,102
29,Sicario: Day of the Soldado,https://www.imdb.com//title/tt5052474/?ref_=ad...,7.1,61,76122,122
...,...,...,...,...,...,...
170,Mid90s,https://www.imdb.com//title/tt5613484/?ref_=ad...,7.5,66,7764,85
171,The Wild Pear Tree,https://www.imdb.com//title/tt6628102/?ref_=ad...,8.4,88,7710,188
172,Gotti,https://www.imdb.com//title/tt1801552/?ref_=ad...,4.9,24,7710,112
173,The Old Man & the Gun,https://www.imdb.com//title/tt2837574/?ref_=ad...,7.1,80,7559,93
174,"Juliet, Naked",https://www.imdb.com//title/tt5607096/?ref_=ad...,6.6,67,7345,97
175,Uncle Drew,https://www.imdb.com//title/tt7334528/?ref_=ad...,5.7,57,7218,103
176,Dogman,https://www.imdb.com//title/tt6768578/?ref_=ad...,7.4,75,7077,103
177,Fahrenheit 11/9,https://www.imdb.com//title/tt8632862/?ref_=ad...,6.3,69,7021,128
178,Wildling,https://www.imdb.com//title/tt5085924/?ref_=ad...,5.5,58,6947,92
179,Father of the Year,https://www.imdb.com//title/tt7256866/?ref_=ad...,5.2,32,6839,94
180,Siberia,https://www.imdb.com//title/tt6494418/?ref_=ad...,4.3,34,6819,104
181,Private Life,https://www.imdb.com//title/tt5536610/?ref_=ad...,7.3,83,6805,123
182,Vice,https://www.imdb.com//title/tt6266538/?ref_=ad...,7.1,61,6679,132
183,Sherlock Gnomes,https://www.imdb.com//title/tt2296777/?ref_=ad...,5.1,36,6607,86
184,Active Measures,https://www.imdb.com//title/tt8135494/?ref_=ad...,8.4,68,6590,109
185,Beautiful Boy,https://www.imdb.com//title/tt1226837/?ref_=ad...,7.3,63,6473,120
186,Climax,https://www.imdb.com//title/tt8359848/?ref_=ad...,7.7,83,6408,95
187,The Mule,https://www.imdb.com//title/tt7959026/?ref_=ad...,7.2,58,6403,116
188,Acts of Violence,https://www.imdb.com//title/tt6684714/?ref_=ad...,5.2,28,6391,86
189,Corredor Assombrado,https://www.imdb.com//title/tt2372251/?ref_=ad...,5.2,56,6384,96
190,Kin,https://www.imdb.com//title/tt6017942/?ref_=ad...,5.7,35,6324,102
191,Billionaire Boys Club,https://www.imdb.com//title/tt5179598/?ref_=ad...,5.6,30,6294,108
192,Instant Family,https://www.imdb.com//title/tt7401588/?ref_=ad...,7.6,57,6166,118
193,They Shall Not Grow Old,https://www.imdb.com//title/tt7905466/?ref_=ad...,8.6,92,6088,99
194,Goosebumps 2: Haunted Halloween,https://www.imdb.com//title/tt5664636/?ref_=ad...,5.7,53,5975,90
195,Proud Mary,https://www.imdb.com//title/tt6421110/?ref_=ad...,4.9,35,5850,89
196,Spinning Man,https://www.imdb.com//title/tt5616294/?ref_=ad...,5.6,44,5840,100
197,Death of a Nation,https://www.imdb.com//title/tt8564902/?ref_=ad...,4.7,1,5386,108
198,Utøya: July 22,https://www.imdb.com//title/tt7959216/?ref_=ad...,7.5,75,5372,93
199,Colette,https://www.imdb.com//title/tt5437928/?ref_=ad...,6.8,74,5338,111

The cool thing is that you can do searches and selection in a fast and clever way

In [46]:
imdb_votes['title']=='Avengers: Infinity War'

0       True
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
170    False
171    False
172    False
173    False
174    False
175    False
176    False
177    False
178    False
179    False
180    False
181    False
182    False
183    False
184    False
185    False
186    False
187    False
188    False
189    False
190    False
191    False
192    False
193    False
194    False
195    False
196    False
197    False
198    False
199    False
Name: title, Length: 200, dtype: bool

BTW, here is what is the [Metascore](https://www.metacritic.com/about-metascores) of IMDb.

Everything works as always...

In [47]:
mask=imdb_votes['title']=='Avengers: Infinity War'
imdb_votes[mask]

,title,url,rating,metascore,votes,runtime
0,Avengers: Infinity War,https://www.imdb.com//title/tt4154756/?ref_=ad...,8.5,68,556607,149

Boolean searches

In [62]:
mask_rating=imdb_votes['rating']==min(imdb_votes['rating'])
imdb_votes[mask_rating]

,title,url,rating,metascore,votes,runtime
116,Slender Man,https://www.imdb.com//title/tt5690360/?ref_=ad...,3.2,30,14969,93

In [64]:
mask_metascore=imdb_votes.metascore<60
imdb_votes[mask_metascore]

,title,url,rating,metascore,votes,runtime
6,Venom,https://www.imdb.com//title/tt1270797/?ref_=ad...,6.8,35,197816,112
8,Jurassic World: Fallen Kingdom,https://www.imdb.com//title/tt4881806/?ref_=ad...,6.2,51,187521,128
11,Bohemian Rhapsody,https://www.imdb.com//title/tt1727824/?ref_=ad...,8.3,49,169065,134
13,Tomb Raider,https://www.imdb.com//title/tt1365519/?ref_=ad...,6.3,48,147098,119
16,Red Sparrow,https://www.imdb.com//title/tt2873282/?ref_=ad...,6.6,53,119504,140
19,Fantastic Beasts: The Crimes of Grindelwald,https://www.imdb.com//title/tt4123430/?ref_=ad...,6.8,52,101976,134
20,Аквамен,https://www.imdb.com//title/tt1477834/?ref_=ad...,7.5,55,101289,143
21,Bird Box,https://www.imdb.com//title/tt2737304/?ref_=ad...,6.8,52,100102,124
22,Rampage,https://www.imdb.com//title/tt2231461/?ref_=ad...,6.1,45,99624,107
23,The Meg,https://www.imdb.com//title/tt4779682/?ref_=ad...,5.7,46,88725,113
25,Maze Runner: The Death Cure,https://www.imdb.com//title/tt4500922/?ref_=ad...,6.3,51,81807,143
26,Pacific Rim: Uprising,https://www.imdb.com//title/tt2557478/?ref_=ad...,5.6,44,80292,111
28,The Cloverfield Paradox,https://www.imdb.com//title/tt2548396/?ref_=ad...,5.6,37,76384,102
31,The Equalizer 2,https://www.imdb.com//title/tt3766354/?ref_=ad...,6.8,50,73048,121
32,The Commuter,https://www.imdb.com//title/tt1590193/?ref_=ad...,6.3,56,72367,105
33,The Predator,https://www.imdb.com//title/tt3829266/?ref_=ad...,5.5,48,72022,107
34,The Nun,https://www.imdb.com//title/tt5814060/?ref_=ad...,5.5,46,71426,96
37,Skyscraper,https://www.imdb.com//title/tt5758778/?ref_=ad...,5.9,51,65557,102
38,Tag,https://www.imdb.com//title/tt2854926/?ref_=ad...,6.6,56,64580,100
42,Den of Thieves,https://www.imdb.com//title/tt1259528/?ref_=ad...,7.0,49,60251,140
49,12 Strong,https://www.imdb.com//title/tt1413492/?ref_=ad...,6.6,54,43571,130
51,Death Wish,https://www.imdb.com//title/tt1137450/?ref_=ad...,6.4,31,42021,107
52,Fifty Shades Freed,https://www.imdb.com//title/tt4477536/?ref_=ad...,4.5,31,39124,105
53,Insidious: The Last Key,https://www.imdb.com//title/tt5726086/?ref_=ad...,5.7,49,37859,103
56,The Spy Who Dumped Me,https://www.imdb.com//title/tt6663582/?ref_=ad...,6.0,52,36135,117
57,Mile 22,https://www.imdb.com//title/tt4560436/?ref_=ad...,6.1,38,35962,94
58,Outlaw King,https://www.imdb.com//title/tt6679794/?ref_=ad...,7.0,59,35388,121
59,The First Purge,https://www.imdb.com//title/tt6133466/?ref_=ad...,5.1,54,33837,98
60,Hotel Transylvania 3: Summer Vacation,https://www.imdb.com//title/tt5220122/?ref_=ad...,6.3,54,32825,97
61,Extinction,https://www.imdb.com//title/tt3201640/?ref_=ad...,5.8,40,32607,95
...,...,...,...,...,...,...
144,Dumplin',https://www.imdb.com//title/tt4878482/?ref_=ad...,6.9,53,10536,110
146,Every Day,https://www.imdb.com//title/tt7026672/?ref_=ad...,6.4,52,10406,97
149,I Can Only Imagine,https://www.imdb.com//title/tt6450186/?ref_=ad...,7.4,30,9880,110
151,Unfriended: Dark Web,https://www.imdb.com//title/tt4761916/?ref_=ad...,5.8,53,9768,92
153,The Nutcracker and the Four Realms,https://www.imdb.com//title/tt5523010/?ref_=ad...,5.6,39,9583,99
154,A Futile and Stupid Gesture,https://www.imdb.com//title/tt5566790/?ref_=ad...,6.8,55,9555,101
156,The Girl in the Spider's Web,https://www.imdb.com//title/tt5177088/?ref_=ad...,6.1,43,8585,117
158,Occupation,https://www.imdb.com//title/tt6774786/?ref_=ad...,5.3,45,8384,119
161,7 Days in Entebbe,https://www.imdb.com//title/tt5466186/?ref_=ad...,5.8,49,8131,107
162,In Darkness,https://www.imdb.com//title/tt5164184/?ref_=ad...,5.7,59,8117,110
166,Breaking In,https://www.imdb.com//title/tt7137846/?ref_=ad...,5.3,42,7923,88
167,Forever My Girl,https://www.imdb.com//title/tt4103724/?ref_=ad...,6.7,36,7867,108
168,White Boy Rick,https://www.imdb.com//title/tt4537896/?ref_=ad...,6.5,59,7856,111
169,Under the Silver Lake,https://www.imdb.com//title/tt5691670/?ref_=ad...,6.4,59,7791,139
172,Gotti,https://www.imdb.com//title/tt1801552/?ref_=ad...,4.9,24,7710,112
175,Uncle Drew,https://www.imdb.com//title/tt7334528/?ref_=ad...,5.7,57,7218,103
178,Wildling,https://www.imdb.com//title/tt5085924/?ref_=ad...,5.5,58,6947,92
179,Father of the Year,https://www.imdb.com//title/tt7256866/?ref_=ad...,5.2,32,6839,94
180,Siberia,https://www.imdb.com//title/tt6494418/?ref_=ad...,4.3,34,6819,104
183,Sherlock Gnomes,https://www.imdb.com//title/tt2296777/?ref_=ad...,5.1,36,6607,86
187,The Mule,https://www.imdb.com//title/tt7959026/?ref_=ad...,7.2,58,6403,116
188,Acts of Violence,https://www.imdb.com//title/tt6684714/?ref_=ad...,5.2,28,6391,86
189,Corredor Assombrado,https://www.imdb.com//title/tt2372251/?ref_=ad...,5.2,56,6384,96
190,Kin,https://www.imdb.com//title/tt6017942/?ref_=ad...,5.7,35,6324,102
191,Billionaire Boys Club,https://www.imdb.com//title/tt5179598/?ref_=ad...,5.6,30,6294,108
192,Instant Family,https://www.imdb.com//title/tt7401588/?ref_=ad...,7.6,57,6166,118
194,Goosebumps 2: Haunted Halloween,https://www.imdb.com//title/tt5664636/?ref_=ad...,5.7,53,5975,90
195,Proud Mary,https://www.imdb.com//title/tt6421110/?ref_=ad...,4.9,35,5850,89
196,Spinning Man,https://www.imdb.com//title/tt5616294/?ref_=ad...,5.6,44,5840,100
197,Death of a Nation,https://www.imdb.com//title/tt8564902/?ref_=ad...,4.7,1,5386,108

### Exercise: select unsufficient rating and unsufficient metascore movies

### Exercise: select movie appreciated by critics, but not by IMDb users

### Exercise: viceversa

### Exercise: calculate the correlation between the metascore and the IMDb rating

### Exercise: calculate the correlation between the rating and the movie length

### Exercise: find the missing movie

Hint: It's a documentary, thus there are not 'actors'!